Repository responsively-org/responsively-app, pull requests merged in 2020-08, with the labels that each got.

#389 Feature/notifications v2
  desktop-app/app/app.html
  desktop-app/app/components/AppNotification/AppNotification.js
  desktop-app/app/components/AppNotification/styles.module.css
  desktop-app/app/components/WebView/index.js
  desktop-app/app/components/common.styles.css
  desktop-app/app/main.dev.js
  desktop-app/app/services/browserSync/index.js
  desktop-app/app/services/db/appMetadata.js
  desktop-app/app/services/db/index.js
Labels: enhancement

#387 screenshot and event mirroring fixed
  desktop-app/app/components/WebView/index.js
  desktop-app/app/components/WebView/screenshotUtil.js
  desktop-app/app/main.dev.js
Labels: bug

#399 Feature/toolbar options cleanup with menu
  desktop-app/app/app.global.css
  desktop-app/app/components/DevicesPreviewer/index.js
  desktop-app/app/components/KebabMenu/index.js
  desktop-app/app/components/KebabMenu/styles.module.css
  desktop-app/app/components/Renderer/index.js
  desktop-app/app/components/Renderer/style.module.css
  desktop-app/app/components/WebView/index.js
  desktop-app/app/components/WebView/style.module.css
  desktop-app/app/components/icons/Kebab.js
  desktop-app/app/reducers/browser.js
  desktop-app/package.json
  desktop-app/yarn.lock
Labels: enhancement

#421 exclude bots from contributors
  website/js/custom/contributors.js
Labels: website
